//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RosterMstLog
    {
        public int Id { get; set; }
        public int RosterID { get; set; }
        public int EmpCode { get; set; }
        public int WeekID { get; set; }
        public System.DateTime rDate { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public int RepMgrCode { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime updatedOn { get; set; }
        public Nullable<int> SwapID { get; set; }
        public Nullable<System.DateTime> LoggedOn { get; set; }
    }
}
