//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCountry
    {
        public int TransID { get; set; }
        public string Country { get; set; }
        public string Capital { get; set; }
        public string Currency { get; set; }
        public string Primary_Language { get; set; }
        public string Market { get; set; }
        public bool Active { get; set; }
    
        public virtual tblMaster tblMaster { get; set; }
    }
}
