//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDesignation
    {
        public int TransID { get; set; }
        public Nullable<int> ID { get; set; }
        public string Designation { get; set; }
        public int LevelID { get; set; }
        public bool Active { get; set; }
        public Nullable<int> SkillsetID { get; set; }
    
        public virtual tblMaster tblMaster { get; set; }
        public virtual tblSkillSet tblSkillSet { get; set; }
    }
}
