//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartmentLinkMst
    {
        public int TransID { get; set; }
        public int FunctionID { get; set; }
        public int DepartmentID { get; set; }
        public int LOBID { get; set; }
        public int SkillSetID { get; set; }
        public int SubSkillSetID { get; set; }
        public bool Active { get; set; }
    }
}
