//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartmentLinkMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDepartmentLinkMst()
        {
            this.tblSkillSets = new HashSet<tblSkillSet>();
            this.tblFunctions = new HashSet<tblFunction>();
            this.tblDepartments = new HashSet<tblDepartment>();
            this.tblLOBs = new HashSet<tblLOB>();
            this.tblSubSkillSets = new HashSet<tblSubSkillSet>();
        }
    
        public int TransID { get; set; }
        public int FunctionID { get; set; }
        public int DepartmentID { get; set; }
        public int LOBID { get; set; }
        public int SkillSetID { get; set; }
        public int SubSkillSetID { get; set; }
        public bool Active { get; set; }
    
        public virtual tblMaster tblMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSkillSet> tblSkillSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFunction> tblFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDepartment> tblDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLOB> tblLOBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubSkillSet> tblSubSkillSets { get; set; }
    }
}
