//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnableDisable
    {
        public int id { get; set; }
        public Nullable<int> MinLevel { get; set; }
        public Nullable<int> MaxLevel { get; set; }
        public Nullable<int> RepMgrAction { get; set; }
        public Nullable<int> RevMgrAction { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<int> RepMgrCan { get; set; }
        public Nullable<int> RevMgrCan { get; set; }
    }
}
