//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIntervalTracker
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Interval { get; set; }
        public string Account { get; set; }
        public string LOB { get; set; }
        public string Sites { get; set; }
        public string Issue { get; set; }
        public string IncidentType { get; set; }
        public string ClientTicket { get; set; }
        public string SitelTicket { get; set; }
        public string Attachment { get; set; }
        public Nullable<int> ActionBy { get; set; }
        public Nullable<System.DateTime> ActionOn { get; set; }
    }
}
