//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeaveType
    {
        public int LeaveID { get; set; }
        public string LeaveText { get; set; }
        public int ShiftCode { get; set; }
        public bool Active { get; set; }
    }
}
