//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster
    {
        public int Employee_ID { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> DOP { get; set; }
        public Nullable<System.DateTime> DOR { get; set; }
        public string DPT { get; set; }
        public Nullable<System.DateTime> DOPS { get; set; }
        public Nullable<byte> EmpStatus { get; set; }
        public Nullable<byte> TrngStatus { get; set; }
        public Nullable<byte> Job_Type { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> DeptLinkId { get; set; }
        public Nullable<int> RepMgrCode { get; set; }
        public string TeamID { get; set; }
        public string ntName { get; set; }
        public Nullable<byte> ResType { get; set; }
        public Nullable<int> BusinessID { get; set; }
        public string Email_Office { get; set; }
        public Nullable<bool> IsReportingManager { get; set; }
    }
}
