//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMaster()
        {
            this.tblDepartmentLinkMsts = new HashSet<tblDepartmentLinkMst>();
            this.tblEmpStatus = new HashSet<tblEmpStatu>();
            this.tblDesignations = new HashSet<tblDesignation>();
            this.tblCountries = new HashSet<tblCountry>();
            this.tblJob_Type = new HashSet<tblJob_Type>();
            this.tblTrainingStatus = new HashSet<tblTrainingStatu>();
            this.tblLevels = new HashSet<tblLevel>();
            this.tblSites = new HashSet<tblSite>();
        }
    
        public int Employee_ID { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> DOP { get; set; }
        public Nullable<System.DateTime> DOR { get; set; }
        public string DPT { get; set; }
        public Nullable<System.DateTime> DOPS { get; set; }
        public Nullable<byte> EmpStatus { get; set; }
        public Nullable<byte> TrngStatus { get; set; }
        public Nullable<byte> Job_Type { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> DeptLinkId { get; set; }
        public Nullable<int> RepMgrCode { get; set; }
        public string TeamID { get; set; }
        public string ntName { get; set; }
        public Nullable<byte> ResType { get; set; }
        public Nullable<int> BusinessID { get; set; }
        public string Email_Office { get; set; }
        public Nullable<bool> IsReportingManager { get; set; }
    
        public virtual tblProfile tblProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDepartmentLinkMst> tblDepartmentLinkMsts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmpStatu> tblEmpStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDesignation> tblDesignations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCountry> tblCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJob_Type> tblJob_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingStatu> tblTrainingStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLevel> tblLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSite> tblSites { get; set; }
    }
}
