//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPincode
    {
        public int Id { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string PostOffice { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
