//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProfile()
        {
            this.tblGenders = new HashSet<tblGender>();
            this.tblMaritalStatus = new HashSet<tblMaritalStatu>();
            this.tblQualifications = new HashSet<tblQualification>();
            this.tblPincodes = new HashSet<tblPincode>();
            this.tblSkills = new HashSet<tblSkill>();
            this.tblLocations = new HashSet<tblLocation>();
        }
    
        public int Employee_ID { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Email_Personal { get; set; }
        public Nullable<long> Contact_Number { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public Nullable<int> Qualification { get; set; }
        public Nullable<bool> Transport { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Landmark { get; set; }
        public Nullable<int> Location { get; set; }
        public string SubLocation { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string City { get; set; }
        public Nullable<int> Total_Work_Experience { get; set; }
        public string Skill1 { get; set; }
        public string Skill2 { get; set; }
        public string Skill3 { get; set; }
        public Nullable<long> Alternate_Contact { get; set; }
        public string EmergencyContactPerson { get; set; }
        public Nullable<long> EmergencyContactNo { get; set; }
        public string UserImage { get; set; }
        public string Updated_by { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        public virtual tblMaster tblMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGender> tblGenders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMaritalStatu> tblMaritalStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQualification> tblQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPincode> tblPincodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSkill> tblSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLocation> tblLocations { get; set; }
    }
}
