//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRstWeek
    {
        public int WeekId { get; set; }
        public int rYear { get; set; }
        public int rWeek { get; set; }
        public System.DateTime FrDate { get; set; }
        public System.DateTime ToDate { get; set; }
    }
}
