//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShiftCode
    {
        public int ShiftID { get; set; }
        public string ShiftCode { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public byte ShiftType { get; set; }
        public Nullable<bool> Exception { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
