//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSwap
    {
        public int ID { get; set; }
        public int SwapID { get; set; }
        public int EmpCode { get; set; }
        public int WeekID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> NewShiftID { get; set; }
        public System.DateTime InitiatedOn { get; set; }
    }
}
