//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSkillSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSkillSet()
        {
            this.tblDesignations = new HashSet<tblDesignation>();
        }
    
        public int ID { get; set; }
        public int TransID { get; set; }
        public string SkillSet { get; set; }
        public bool Active { get; set; }
        public Nullable<int> SkillSetID { get; set; }
    
        public virtual tblDepartmentLinkMst tblDepartmentLinkMst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDesignation> tblDesignations { get; set; }
    }
}
