//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSwapMst
    {
        public int ID { get; set; }
        public int Requestor { get; set; }
        public int WeekID { get; set; }
        public System.DateTime InitiatedOn { get; set; }
        public Nullable<short> Level1Action { get; set; }
        public Nullable<System.DateTime> Level1ActionOn { get; set; }
        public Nullable<int> Level2EmpCode { get; set; }
        public Nullable<short> Level2Action { get; set; }
        public Nullable<System.DateTime> Level2ActionOn { get; set; }
    }
}
